# Generated by Django 3.2.9 on 2021-12-05 11:50

from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields
import filer.fields.folder


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filer', '0015_auto_20211105_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Mechanix/Event')),
                ('title', models.CharField(max_length=128)),
                ('subtitle', models.CharField(max_length=128)),
                ('description', djangocms_text_ckeditor.fields.HTMLField()),
                ('date', models.DateField(blank=True, null=True)),
                ('passed', models.BooleanField()),
                ('start', models.TimeField(blank=True, null=True)),
                ('doors', models.TimeField(blank=True, null=True)),
                ('imageFolder', filer.fields.folder.FilerFolderField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='filer.folder')),
            ],
        ),
    ]
