# Generated by Django 3.2.9 on 2021-12-07 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20211207_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='externalButtonText',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='externalButtonUrl',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
