# Generated by Django 3.2.9 on 2021-12-07 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fobi', '0016_auto_20211206_1039'),
        ('events', '0004_auto_20211207_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='forms',
            field=models.ManyToManyField(blank=True, to='fobi.FormEntry'),
        ),
    ]
