# Generated by Django 3.2.9 on 2021-12-07 13:55

from django.db import migrations, models
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_forms'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description_en',
            field=djangocms_text_ckeditor.fields.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='description_nl',
            field=djangocms_text_ckeditor.fields.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='subtitle_en',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='subtitle_nl',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='title_en',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='title_nl',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
