# Generated by Django 3.2.9 on 2021-12-07 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20211207_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='currentTicketNumber',
            field=models.IntegerField(default=0),
        ),
    ]
