# Generated by Django 3.2.9 on 2021-11-05 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0023_auto_20211105_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='website_menuitem', serialize=False, to='cms.cmsplugin')),
                ('displayName', models.CharField(max_length=128)),
                ('pageID', models.CharField(max_length=16)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
