# Generated by Django 3.2.9 on 2021-12-07 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20211207_1213'),
        ('cms', '0023_auto_20211206_1039'),
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventGridItem',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='website_eventgriditem', serialize=False, to='cms.cmsplugin')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
