# Generated by Django 3.2.9 on 2021-11-06 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0023_auto_20211105_1037'),
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MastheadImage',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='website_mastheadimage', serialize=False, to='cms.cmsplugin')),
                ('image', models.ImageField(upload_to='Mechanix')),
                ('alt', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
