# Generated by Django 3.2.9 on 2021-11-06 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0023_auto_20211105_1037'),
        ('website', '0002_mastheadimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Masthead',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='website_masthead', serialize=False, to='cms.cmsplugin')),
                ('background', models.ImageField(upload_to='Mechanix')),
                ('alt', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='MastheadButton',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='website_mastheadbutton', serialize=False, to='cms.cmsplugin')),
                ('link', models.CharField(max_length=128)),
                ('text', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='MastheadContent',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='website_mastheadcontent', serialize=False, to='cms.cmsplugin')),
                ('htmlClasses', models.CharField(max_length=256)),
                ('text', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.DeleteModel(
            name='MastheadImage',
        ),
    ]
