# Generated by Django 3.2.9 on 2021-11-08 12:59

from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0023_auto_20211105_1037'),
        ('website', '0005_contentgrid_contentgridentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentFlow',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='website_contentflow', serialize=False, to='cms.cmsplugin')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='ContentFlowEntryHTML',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='website_contentflowentryhtml', serialize=False, to='cms.cmsplugin')),
                ('text', djangocms_text_ckeditor.fields.HTMLField()),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='ContentFlowEntryImage',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='website_contentflowentryimage', serialize=False, to='cms.cmsplugin')),
                ('image', models.ImageField(upload_to='Mechanix/Flow')),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=256, null=True)),
                ('content', models.CharField(blank=True, max_length=2048, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='ContentTeam',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='website_contentteam', serialize=False, to='cms.cmsplugin')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='ContentTeamEntry',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='website_contentteamentry', serialize=False, to='cms.cmsplugin')),
                ('image', models.ImageField(upload_to='Mechanix/Team')),
                ('name', models.CharField(max_length=128)),
                ('function', models.CharField(max_length=128)),
                ('linkedin', models.CharField(blank=True, max_length=512, null=True)),
                ('mail', models.CharField(blank=True, max_length=512, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
