# Generated by Django 3.2.9 on 2021-11-08 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0023_auto_20211105_1037'),
        ('website', '0006_contentflow_contentflowentryhtml_contentflowentryimage_contentteam_contentteamentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentGallery',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='website_contentgallery', serialize=False, to='cms.cmsplugin')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='ContentGalleryEntry',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='website_contentgalleryentry', serialize=False, to='cms.cmsplugin')),
                ('image', models.ImageField(upload_to='Mechanix/Gallery')),
                ('alt', models.CharField(max_length=512)),
                ('url', models.CharField(blank=True, max_length=512, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='website_footer', serialize=False, to='cms.cmsplugin')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='FooterFontAwesomeEntry',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='website_footerfontawesomeentry', serialize=False, to='cms.cmsplugin')),
                ('faClass', models.CharField(max_length=512)),
                ('url', models.CharField(max_length=512)),
                ('pos', models.CharField(choices=[('L', 'Left'), ('M', 'Middle'), ('R', 'Right')], max_length=16)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='FooterTextEntry',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='website_footertextentry', serialize=False, to='cms.cmsplugin')),
                ('text', models.CharField(max_length=512)),
                ('url', models.CharField(blank=True, max_length=512, null=True)),
                ('pos', models.CharField(choices=[('L', 'Left'), ('M', 'Middle'), ('R', 'Right')], max_length=16)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
