# Generated by Django 3.2.9 on 2021-11-08 15:22

from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0023_auto_20211105_1037'),
        ('website', '0007_contentgallery_contentgalleryentry_footer_footerfontawesomeentry_footertextentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterHTMLEntry',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='website_footerhtmlentry', serialize=False, to='cms.cmsplugin')),
                ('text', djangocms_text_ckeditor.fields.HTMLField()),
                ('pos', models.CharField(choices=[('L', 'Left'), ('M', 'Middle'), ('R', 'Right')], max_length=16)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
