# Generated by Django 3.2.9 on 2021-11-08 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_footerhtmlentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentteamentry',
            name='function',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
