# Generated by Django 3.2.9 on 2021-11-11 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_contentteamentry_function'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentteamentry',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Mechanix/Team'),
        ),
    ]
