# Generated by Django 3.2.9 on 2021-11-13 17:47

from django.db import migrations, models
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20211113_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentteamentry',
            name='image',
        ),
        migrations.AddField(
            model_name='contentteamentry',
            name='squareImage',
            field=models.ImageField(blank=True, null=True, upload_to='Mechanix/Team/Square'),
        ),
        migrations.AddField(
            model_name='contentteamentry',
            name='text',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentteamentry',
            name='verticalImage',
            field=models.ImageField(blank=True, null=True, upload_to='Mechanix/Team/Vertical'),
        ),
    ]
