# Generated by Django 3.2.9 on 2021-11-23 17:13

from django.db import migrations
import django.db.models.deletion
import filer.fields.folder


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0015_auto_20211105_1038'),
        ('website', '0012_auto_20211113_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentgridentry',
            name='imageFolder',
            field=filer.fields.folder.FilerFolderField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='filer.folder'),
        ),
    ]
