# Generated by Django 3.2.9 on 2021-12-03 19:02

from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields
import filer.fields.folder


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0015_auto_20211105_1038'),
        ('cms', '0023_auto_20211105_1037'),
        ('website', '0013_contentgridentry_imagefolder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='website_event', serialize=False, to='cms.cmsplugin')),
                ('image', models.ImageField(upload_to='Mechanix/Event')),
                ('title', models.CharField(max_length=128)),
                ('subtitle', models.CharField(max_length=128)),
                ('description', djangocms_text_ckeditor.fields.HTMLField()),
                ('buttonUrl', models.CharField(blank=True, max_length=256, null=True)),
                ('buttonText', models.CharField(blank=True, max_length=256, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('passed', models.BooleanField()),
                ('start', models.TimeField(blank=True, null=True)),
                ('doors', models.TimeField(blank=True, null=True)),
                ('imageFolder', filer.fields.folder.FilerFolderField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='filer.folder')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.DeleteModel(
            name='ContentGridEntry',
        ),
    ]
