# Generated by Django 3.2.9 on 2021-12-04 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0023_auto_20211105_1037'),
        ('website', '0014_auto_20211203_1902'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
